name: Deploy to server

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
    types: [merged]

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: 'Badge.team OTA'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      # Fix timestamps for differential update
      - name: Restore file timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Upload with Rsync
        uses: SamKirkland/web-deploy@v1
        with:
          source-path: '.'
          target-server: ${{ vars.HOST }}
          ssh-port:      ${{ vars.SSH_PORT }}
          remote-user:   ${{ vars.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ${{ vars.WEBROOT }}
