name: Pull request
run-name: "Checks: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"

on:
  pull_request:
  merge_group:

jobs:
  check-version-consistency:
    name: Check version consistency
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - id: check
        name: Run version consistency check
        run: |
          set +e
          check_output=$(./check_versions.sh 2>&1)
          failed_checks=$?

          echo "$check_output"
          echo "failed_checks=$failed_checks" >> $GITHUB_OUTPUT

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          cat << $EOF >> $GITHUB_STEP_SUMMARY
          # Version consistency check $([ $failed_checks = 0 ] && echo '✅' || echo '❌')
          \`\`\`
          $check_output
          \`\`\`
          $EOF

          exit $failed_checks
